"""Design variables: what a study varies, and the values it varies over.

Three kinds, deliberately no more. A linear range, an explicit list of numbers,
and a list of categories. There is no expression language and no user-supplied
callable: a study definition that could contain arbitrary code could not be
fingerprinted, serialised, or reasoned about, and "the study ran something the
user typed" is not a provenance record.

Two properties matter more than they look:

**Exact endpoints.** A linear range is generated by index, ``start + i·span/(n-1)``,
with the first and last values assigned literally. Accumulating ``value += step``
drifts, and a study whose top-of-range O/F is 4.499999999999998 has silently
stopped being the study that was defined.

**A stage.** Every variable declares which evaluation stage it belongs to. That
is what lets the planner know an area ratio cannot change a chamber state, and
it is the entire basis of the solve-reuse guarantee. The stage names are the
domain's, not this module's -- the generic layer only knows they are ordered.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

__all__ = [
    "VariableDomain",
    "DesignVariable",
    "LinearRangeVariable",
    "ExplicitNumericVariable",
    "CategoricalVariable",
    "linear_range",
]


@dataclass(frozen=True, slots=True)
class VariableDomain:
    """The values a variable is allowed to take.

    Checked when the variable is constructed rather than when the study runs,
    so an impossible range is refused while the user is still looking at the
    form that produced it.
    """

    minimum: float | None = None
    maximum: float | None = None
    exclusive_minimum: bool = False
    exclusive_maximum: bool = False

    def contains(self, value: float) -> bool:
        if self.minimum is not None:
            if self.exclusive_minimum and not value > self.minimum:
                return False
            if not self.exclusive_minimum and not value >= self.minimum:
                return False
        if self.maximum is not None:
            if self.exclusive_maximum and not value < self.maximum:
                return False
            if not self.exclusive_maximum and not value <= self.maximum:
                return False
        return True

    def describe(self) -> str:
        if self.minimum is None and self.maximum is None:
            return "unbounded"
        low = ("−∞" if self.minimum is None
               else f"{self.minimum:g}{'' if not self.exclusive_minimum else '+'}")
        high = ("∞" if self.maximum is None
                else f"{self.maximum:g}{'' if not self.exclusive_maximum else '−'}")
        return f"[{low}, {high}]"


def linear_range(start: float, end: float, count: int) -> tuple[float, ...]:
    """``count`` values from ``start`` to ``end``, endpoints exact.

    Generated by index rather than by accumulation. ``value += step`` repeated
    40 times leaves the last point short or long by several ulp, and the
    endpoints are the two values a user is most likely to have chosen
    deliberately.

    ``count == 1`` returns ``start`` alone: a single-point "range" is a fixed
    value, and averaging it with the end would silently study something else.
    """
    if not isinstance(count, int) or isinstance(count, bool):
        raise TypeError(f"count must be an int, got {count!r}")
    if count < 1:
        raise ValueError(f"count must be at least 1, got {count}")
    for name, value in (("start", start), ("end", end)):
        if not math.isfinite(float(value)):
            raise ValueError(f"{name} must be finite, got {value!r}")
    start, end = float(start), float(end)
    if count == 1:
        return (start,)
    span = end - start
    last = count - 1
    values = [start]
    values.extend(start + span * index / last for index in range(1, last))
    values.append(end)
    return tuple(values)


@dataclass(frozen=True, slots=True)
class DesignVariable:
    """One thing a study varies, with the values it takes.

    Subclasses differ only in how ``values`` is produced; everything downstream
    -- enumeration, keys, fingerprints, display -- works on the resolved tuple,
    so a new variable kind cannot change how a study is planned.

    Attributes:
        key: The stable scientific identifier. Never a display string: a label
            can be reworded, and a stored study must still resolve.
        label: What a person reads.
        unit: The canonical unit the values are in. Empty for dimensionless
            and for categorical variables. Display units are the application's
            business, never this layer's.
        stage: Which evaluation stage this variable belongs to. The generic
            layer treats it as an opaque name ordered by the study's
            ``stage_order``; the domain decides what the names mean.
    """

    key: str
    label: str
    stage: str
    unit: str = ""
    domain: VariableDomain = field(default_factory=VariableDomain)

    def __post_init__(self) -> None:
        if not self.key or not self.key.strip():
            raise ValueError("a design variable needs a non-empty key")
        if not self.stage or not self.stage.strip():
            raise ValueError(f"variable {self.key!r} needs an evaluation stage")

    @property
    def values(self) -> tuple[Any, ...]:
        raise NotImplementedError

    @property
    def count(self) -> int:
        return len(self.values)

    @property
    def is_numeric(self) -> bool:
        return True

    def describe(self) -> str:
        raise NotImplementedError

    def canonical(self) -> dict[str, Any]:
        """The fingerprintable form. Ordered, and free of display-only fields."""
        return {
            "kind": type(self).__name__,
            "key": self.key,
            "stage": self.stage,
            "unit": self.unit,
            "values": list(self.values),
        }

    def _validate_values(self, values: tuple[Any, ...]) -> None:
        if not values:
            raise ValueError(f"variable {self.key!r} has no values to study")
        for value in values:
            number = float(value)
            if not math.isfinite(number):
                raise ValueError(
                    f"variable {self.key!r} has a non-finite value {value!r}")
            if not self.domain.contains(number):
                raise ValueError(
                    f"variable {self.key!r} value {value!r} is outside its "
                    f"allowed domain {self.domain.describe()}")


@dataclass(frozen=True, slots=True)
class LinearRangeVariable(DesignVariable):
    """``count`` evenly spaced values from ``start`` to ``end``.

    ``start``/``end``/``count`` rather than ``start``/``end``/``step`` because
    the point count is then exact and known before anything runs -- which is
    what the workload preview needs, and what stops a study from producing 40
    or 42 points depending on rounding.
    """

    start: float = 0.0
    end: float = 1.0
    count: int = 2

    def __post_init__(self) -> None:
        DesignVariable.__post_init__(self)
        self._validate_values(self.values)

    @property
    def values(self) -> tuple[float, ...]:
        return linear_range(self.start, self.end, self.count)

    def describe(self) -> str:
        unit = f" {self.unit}" if self.unit else ""
        if self.count == 1:
            return f"{self.start:g}{unit}"
        return (f"{self.start:g} → {self.end:g}{unit}, "
                f"{self.count} points")

    def canonical(self) -> dict[str, Any]:
        return {**DesignVariable.canonical(self),
                "start": float(self.start), "end": float(self.end),
                "count": int(self.count)}


@dataclass(frozen=True, slots=True)
class ExplicitNumericVariable(DesignVariable):
    """A list of numbers chosen individually.

    For the case a linear range cannot express: area ratios of 10, 20, 40, 80,
    or a handful of chamber pressures a programme actually uses.
    """

    entries: tuple[float, ...] = ()

    def __post_init__(self) -> None:
        DesignVariable.__post_init__(self)
        self._validate_values(self.values)
        if len(set(self.values)) != len(self.values):
            raise ValueError(
                f"variable {self.key!r} repeats a value; a duplicated point "
                "would be evaluated twice and appear twice in every ranking")

    @property
    def values(self) -> tuple[float, ...]:
        return tuple(float(value) for value in self.entries)

    def describe(self) -> str:
        unit = f" {self.unit}" if self.unit else ""
        shown = ", ".join(f"{value:g}" for value in self.values[:6])
        more = "" if len(self.values) <= 6 else f", … ({len(self.values)} total)"
        return f"{shown}{more}{unit}"


@dataclass(frozen=True, slots=True)
class CategoricalVariable(DesignVariable):
    """A choice among named options.

    The options are opaque strings to this layer. Whatever they mean -- a
    propellant pair, a chemistry mode -- is resolved by the evaluator that was
    given them, and validating that they resolve is the evaluator's job, not
    this module's.
    """

    options: tuple[str, ...] = ()

    def __post_init__(self) -> None:
        DesignVariable.__post_init__(self)
        if not self.options:
            raise ValueError(f"variable {self.key!r} has no options to study")
        if len(set(self.options)) != len(self.options):
            raise ValueError(f"variable {self.key!r} repeats an option")

    @property
    def values(self) -> tuple[str, ...]:
        return tuple(str(option) for option in self.options)

    @property
    def is_numeric(self) -> bool:
        return False

    def describe(self) -> str:
        return ", ".join(self.values)
