import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import RocketForge 1.0
import "../../theme"
import "../../components"

/*
 * Generated Fanno table.
 *
 * Every row is computed by RocketForge for the chosen gamma and Mach range.
 *
 * There is no published-table comparison here and the page says why: the
 * supplied Anderson volume has appendices for isentropic flow, normal shocks
 * and the Prandtl–Meyer function, and none for Fanno flow. Rather than invent
 * one for visual symmetry, the validation panel names the checks that actually
 * back these numbers — two of which run against published tables RocketForge
 * does hold.
 */
Item {
    id: page

    property int selectedRow: -1
    property real jumpMach: 1.0

    function jumpTo(mach) {
        var row = Fanno.rowNearest(mach)
        if (row < 0)
            return
        page.selectedRow = row
        Fanno.selectRow(row)
        table.scrollToRow(row)
    }

    function applySettings() {
        Fanno.regenerateTable()
        page.selectedRow = -1
    }

    ColumnLayout {
        anchors.fill: parent
        spacing: Metrics.spacing.m

        RFPanel {
            Layout.fillWidth: true
            Layout.preferredHeight: 108
            contentSpacing: Metrics.spacing.s

            RowLayout {
                Layout.fillWidth: true
                spacing: Metrics.spacing.m

                RFBoundNumberField {
                    Layout.preferredWidth: 118
                    label: "γ"
                    value: Fanno.tableGamma
                    digits: 4
                    decimals: 4
                    step: 0.005
                    onValueEdited: function (v) { Fanno.tableGamma = v }
                }
                RFBoundNumberField {
                    Layout.preferredWidth: 118
                    label: "Start M"
                    value: Fanno.tableStart
                    digits: 3
                    decimals: 3
                    step: 0.01
                    onValueEdited: function (v) { Fanno.tableStart = v }
                }
                RFBoundNumberField {
                    Layout.preferredWidth: 118
                    label: "End M"
                    value: Fanno.tableEnd
                    digits: 3
                    decimals: 3
                    step: 0.1
                    onValueEdited: function (v) { Fanno.tableEnd = v }
                }
                RFBoundNumberField {
                    Layout.preferredWidth: 118
                    label: "Step"
                    value: Fanno.tableStep
                    digits: 3
                    decimals: 3
                    step: 0.01
                    onValueEdited: function (v) { Fanno.tableStep = v }
                }

                ColumnLayout {
                    Layout.preferredWidth: 230
                    spacing: 3
                    RFSectionLabel { text: "Branch" }
                    RFSegmentedControl {
                        Layout.fillWidth: true
                        model: ["Both", "Subsonic", "Supersonic"]
                        currentIndex: Fanno.tableBranch === "both" ? 0
                                    : Fanno.tableBranch === "subsonic" ? 1 : 2
                        onSelected: function (index) {
                            Fanno.tableBranch = ["both", "subsonic", "supersonic"][index]
                            page.applySettings()
                        }
                    }
                }

                ColumnLayout {
                    Layout.preferredWidth: 150
                    spacing: 3
                    RFSectionLabel { text: "Precision" }
                    RFSegmentedControl {
                        Layout.fillWidth: true
                        model: ["4", "6", "8"]
                        currentIndex: Fanno.tablePrecision === 4 ? 0
                                    : Fanno.tablePrecision === 6 ? 1 : 2
                        useMonoFont: true
                        onSelected: function (index) {
                            Fanno.tablePrecision = [4, 6, 8][index]
                        }
                    }
                }

                Item { Layout.fillWidth: true }

                RFButton {
                    text: "Generate"
                    variant: "primary"
                    onClicked: page.applySettings()
                }
            }

            RowLayout {
                Layout.fillWidth: true
                spacing: Metrics.spacing.m

                Text {
                    Layout.fillWidth: true
                    text: "Generated by RocketForge — the friction column is 4 f_F L*/D with "
                          + "f_F the Fanning friction factor, which is the same group as "
                          + "f_D L*/D under the Darcy convention."
                    wrapMode: Text.WordWrap
                    color: Theme.textMuted
                    font.family: Typography.sans
                    font.pixelSize: Typography.meta
                }

                RFBoundNumberField {
                    Layout.preferredWidth: 132
                    label: "Jump to M"
                    value: page.jumpMach
                    digits: 3
                    decimals: 3
                    step: 0.1
                    onValueEdited: function (v) { page.jumpMach = v }
                }
                RFButton {
                    text: "Go"
                    variant: "quiet"
                    compact: true
                    onClicked: page.jumpTo(page.jumpMach)
                }
                RFButton {
                    text: "Copy table"
                    variant: "quiet"
                    compact: true
                    onClicked: Fanno.copyTable()
                }
            }
        }

        RowLayout {
            Layout.fillWidth: true
            Layout.fillHeight: true
            spacing: Metrics.spacing.m

            RFPanel {
                title: "Fanno line"
                Layout.fillWidth: true
                Layout.fillHeight: true

                trailing: Component {
                    RFStatusChip {
                        text: "RocketForge generated"
                        tone: "success"
                        showDot: false
                    }
                }

                RFEngineeringTable {
                    id: table
                    Layout.fillWidth: true
                    Layout.fillHeight: true
                    visible: Fanno.tableRowCount > 0

                    model: Fanno.tableModel
                    columns: Fanno.tableColumns
                    markedRow: Fanno.sonicRow
                    markedLabel: "SONIC · CHOKING"
                    selectedRow: page.selectedRow
                    firstColumnWidth: 104
                    // The sonic row separates two physical branches, so the
                    // region edge earns its keep here.
                    showRegionEdge: true
                    // valueAreaWidth already excludes the first column and
                    // the marker gutter, so every column stays in view.
                    columnWidth: Math.min(190, Math.max(124,
                                 valueAreaWidth / Math.max(1, columns.length - 1)))

                    onRowClicked: function (row) {
                        page.selectedRow = row
                        Fanno.selectRow(row)
                    }
                    onRowActivated: function (row) {
                        Fanno.setMachAndSolve(Fanno.tableModel.machAt(row))
                        Fanno.requestTab(0)
                    }
                }

                RFEmptyState {
                    Layout.fillWidth: true
                    Layout.fillHeight: true
                    visible: Fanno.tableRowCount === 0
                    tag: "Table"
                    title: Fanno.tableMessage !== "" ? "Table not generated" : "No rows"
                    body: Fanno.tableMessage !== "" ? Fanno.tableMessage
                                                    : "Adjust the range and press Generate."
                }

                Text {
                    Layout.fillWidth: true
                    text: Fanno.tableFooter
                    wrapMode: Text.WordWrap
                    color: Theme.textMuted
                    font.family: Typography.sans
                    font.pixelSize: Typography.meta
                }
            }

            // ---- validation, not a reference-table comparison ---------------
            RFPanel {
                title: "Reference validation"
                Layout.preferredWidth: 372
                Layout.fillHeight: true
                contentSpacing: Metrics.spacing.s

                trailing: Component {
                    RFStatusChip {
                        text: Fanno.validationStatus
                        tone: Fanno.validationStatus === "PASS" ? "success" : "warning"
                        showDot: false
                    }
                }

                Text {
                    Layout.fillWidth: true
                    text: Fanno.referenceMessage
                    wrapMode: Text.WordWrap
                    lineHeight: Typography.proseLineHeight
                    lineHeightMode: Text.ProportionalHeight
                    color: Theme.textSecondary
                    font.family: Typography.sans
                    font.pixelSize: Typography.bodySmall
                }

                RFDivider {}

                RFSectionLabel { text: "What backs these numbers" }

                Repeater {
                    model: Fanno.validationChecks

                    delegate: ColumnLayout {
                        required property var modelData
                        Layout.fillWidth: true
                        Layout.bottomMargin: Metrics.spacing.xs
                        spacing: 2

                        RowLayout {
                            Layout.fillWidth: true
                            spacing: Metrics.spacing.s

                            Text {
                                Layout.fillWidth: true
                                text: modelData.name
                                wrapMode: Text.WordWrap
                                color: Theme.text
                                font.family: Typography.sans
                                font.pixelSize: Typography.bodySmall
                            }
                            RFStatusChip {
                                text: modelData.status
                                tone: modelData.status === "PASS" ? "success" : "warning"
                                showDot: false
                            }
                        }

                        Text {
                            Layout.fillWidth: true
                            text: modelData.detail
                            wrapMode: Text.WordWrap
                            lineHeight: Typography.proseLineHeight
                            lineHeightMode: Text.ProportionalHeight
                            color: Theme.textMuted
                            font.family: Typography.sans
                            font.pixelSize: Typography.meta
                        }
                    }
                }

                Item { Layout.fillHeight: true }

                Text {
                    Layout.fillWidth: true
                    text: Fanno.validationCitation
                    wrapMode: Text.WordWrap
                    lineHeight: Typography.proseLineHeight
                    lineHeightMode: Text.ProportionalHeight
                    color: Theme.textMuted
                    font.family: Typography.sans
                    font.pixelSize: Typography.meta
                }
            }
        }
    }
}
