"""What backs the Fanno, Rayleigh and nozzle numbers, said on the page.

The other four compressible modules each compare against a published table
row by row: Anderson's Appendix A, B or C. Fanno and Rayleigh cannot, because
**the supplied Anderson volume has no Fanno or Rayleigh appendix** -- its
appendices are isentropic flow, normal shocks, the Prandtl-Meyer function, and
two standard atmospheres. Inventing one for visual symmetry would be the worst
thing this module could do, so the pages say plainly that there is none and
name what does back the numbers instead.

Four things do, and three of them run against published tables RocketForge
already holds and has already validated:

1. **A published Fanno/Rayleigh table that does exist** -- NASA/TM-2006-214086,
   a public-domain NASA Glenn technical memorandum which tabulates both
   families. Compared value by value at its own printed precision.
2. **The Fanno stagnation-pressure column is the isentropic area ratio.**
   ``p0/p0* == A/A*`` exactly, because p0 A* is constant for a given mass flow
   and stagnation temperature. So that whole column is checked against
   Anderson's *published* Appendix A.
3. **The Fanno temperature column follows from Appendix A too**, since
   ``T/T* == ((gamma+1)/2)(T/T0)`` and T0/T is a printed column there.
4. **The Fanno-Rayleigh intersection theorem.** The two states across a normal
   shock lie on both a common Fanno line and a common Rayleigh line, so the
   ratios between them must equal the shock's own -- which are checked against
   the *published* Appendix B. This is the strongest check available, because
   it ties both new modules to a printed table through a classical theorem
   rather than through anything RocketForge computed.

This module reads the shipped dataset and reports the outcome. It runs no
comparison of its own: the assertions live in the test suite, and what is
published here is a summary of what that suite covers, with citations.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache

from .reference_comparison import reference_root

__all__ = [
    "ValidationCheck",
    "ValidationSummary",
    "fanno_validation",
    "rayleigh_validation",
    "nozzle_validation",
    "NO_PUBLISHED_APPENDIX",
    "NO_PUBLISHED_NOZZLE_TABLE",
]

#: Said on both pages, because the absence is a fact about the source rather
#: than a gap in the module.
NO_PUBLISHED_APPENDIX = (
    "Anderson's Fundamentals of Aerodynamics has no Fanno or Rayleigh appendix — "
    "its tables are isentropic flow, normal shocks and the Prandtl-Meyer function — "
    "so there is no row-by-row comparison against it here, and none is invented. "
    "The table above is generated by RocketForge; the checks below are what "
    "establish that it is right."
)


@dataclass(frozen=True, slots=True)
class ValidationCheck:
    """One named check, its outcome, and where its authority comes from."""

    name: str
    status: str          # "PASS"
    detail: str


@dataclass(frozen=True, slots=True)
class ValidationSummary:
    """Everything a validation panel needs, with nothing computed on the fly."""

    status: str
    message: str
    citation: str
    checks: tuple[ValidationCheck, ...]


@lru_cache(maxsize=4)
def _dataset(name: str) -> dict:
    """The shipped reference file, read once."""
    return json.loads((reference_root() / name).read_text(encoding="utf-8"))


def _citation(payload: dict) -> str:
    return f"{payload['source']}  ·  accessed {payload['accessed']}"


def _published_check(payload: dict, family: str) -> ValidationCheck:
    cases = payload["cases"]
    values = sum(len(case["values"]) for case in cases)
    tables = sorted({case["table"].split(" - ")[0].strip() for case in cases})
    return ValidationCheck(
        name=f"Published {family} table, value by value",
        status="PASS",
        detail=(
            f"{values} printed values across {len(cases)} Mach numbers, from "
            f"{', '.join(tables)} of NASA/TM-2006-214086, each compared at half a unit "
            "in its own last printed figure."
        ),
    )


def fanno_validation() -> ValidationSummary:
    """What backs the Fanno numbers."""
    payload = _dataset("fanno_nasa_tm_2006_214086.json")
    return ValidationSummary(
        status="PASS",
        message=NO_PUBLISHED_APPENDIX,
        citation=_citation(payload),
        checks=(
            _published_check(payload, "Fanno"),
            ValidationCheck(
                name="The friction convention itself",
                status="PASS",
                detail=(
                    "The published column is the Fanning group 4 f_F L*/D. Under a Darcy "
                    "reading every value would be four times smaller, so agreement "
                    "confirms the convention and not only the algebra."
                ),
            ),
            ValidationCheck(
                name="p₀/p₀* against Anderson Appendix A",
                status="PASS",
                detail=(
                    "p₀/p₀* equals the isentropic A/A* exactly, because p₀A* is constant "
                    "for a given mass flow and T₀. That column is therefore checked "
                    "against a published table this application already holds and "
                    "verifies row by row."
                ),
            ),
            ValidationCheck(
                name="T/T* against Anderson Appendix A",
                status="PASS",
                detail=(
                    "T/T* is ((γ+1)/2)(T/T₀), and T₀/T is a printed Appendix A column, so "
                    "the temperature column follows from the same published table."
                ),
            ),
            ValidationCheck(
                name="The Fanno–Rayleigh intersection theorem",
                status="PASS",
                detail=(
                    "The two states across a normal shock lie on a common Fanno line, so "
                    "the Fanno ratios between them must equal the shock's own — which are "
                    "checked against the published Appendix B. Verified for p, T and p₀."
                ),
            ),
            ValidationCheck(
                name="γ-general identities at four γ",
                status="PASS",
                detail=(
                    "Every relation is additionally exercised at γ = 1.2, 1.3, 1.4 and "
                    "1.66 against identities that hold at any γ, so agreement at 1.4 "
                    "cannot hide a wrong coefficient."
                ),
            ),
        ),
    )


def rayleigh_validation() -> ValidationSummary:
    """What backs the Rayleigh numbers."""
    payload = _dataset("rayleigh_nasa_tm_2006_214086.json")
    return ValidationSummary(
        status="PASS",
        message=NO_PUBLISHED_APPENDIX,
        citation=_citation(payload),
        checks=(
            _published_check(payload, "Rayleigh"),
            ValidationCheck(
                name="The published inverse roots",
                status="PASS",
                detail=(
                    "The report's worked T₀/T₀* inversions are reproduced on both "
                    "branches, and the two roots are asserted to be genuinely different "
                    "ducts rather than the same one found twice."
                ),
            ),
            ValidationCheck(
                name="The Fanno–Rayleigh intersection theorem",
                status="PASS",
                detail=(
                    "The two states across a normal shock also lie on a common Rayleigh "
                    "line, so the Rayleigh p and T ratios between them must equal the "
                    "shock's own — checked against the published Appendix B."
                ),
            ),
            ValidationCheck(
                name="Both critical points, in closed form",
                status="PASS",
                detail=(
                    "The static-temperature maximum at M = 1/√γ with value (γ+1)²/(4γ), "
                    "and the stagnation-temperature maximum of exactly 1 at M = 1, are "
                    "each verified against an independent numerical determination at "
                    "four γ — not merely sampled on a grid."
                ),
            ),
            ValidationCheck(
                name="Distinct from the isentropic and Fanno families",
                status="PASS",
                detail=(
                    "Every Rayleigh starred ratio is asserted to differ from its "
                    "isentropic counterpart, which guards against a copy-paste between "
                    "the two modules."
                ),
            ),
            ValidationCheck(
                name="γ-general identities at four γ",
                status="PASS",
                detail=(
                    "Exercised at γ = 1.2, 1.3, 1.4 and 1.66 against identities that "
                    "hold at any γ."
                ),
            ),
        ),
    )


#: Said on the nozzle page. The absence is a fact about the source, and the
#: construction that replaces it is described rather than glossed over.
NO_PUBLISHED_NOZZLE_TABLE = (
    "Anderson's Fundamentals of Aerodynamics has no nozzle appendix and no printed "
    "back-pressure regime table, so there is no row-by-row comparison here and none "
    "is invented. What replaces it is stronger than a table lookup: complete nozzle "
    "cases are assembled out of printed rows, and RocketForge must then rediscover "
    "published stations it was never given."
)


def nozzle_validation() -> ValidationSummary:
    """What backs the nozzle numbers."""
    payload = _dataset("nozzle_anderson6_constructed.json")
    source = payload["source"]
    cases = payload["cases"]
    values = sum(len(case["expected"]) for case in cases)
    citation = (f"{source['author']}, {source['title']}, {source['edition']} — "
                f"{source['appendices']}")
    return ValidationSummary(
        status="PASS",
        message=NO_PUBLISHED_NOZZLE_TABLE,
        citation=citation,
        checks=(
            ValidationCheck(
                name="End-to-end cases built from printed rows",
                status="PASS",
                detail=(
                    f"{len(cases)} nozzle cases covering all seven regimes, "
                    f"{values} published values in total. The geometry and the back "
                    "pressure of each case are assembled from printed Appendix A and B "
                    "rows, and the expected answers are printed rows too."
                ),
            ),
            ValidationCheck(
                name="The internal shock rediscovers four published numbers",
                status="PASS",
                detail=(
                    "Given only an area ratio and a back pressure built from four "
                    "printed values, the solver places the shock at Appendix A's "
                    "M = 2.00 area ratio (1.687), reproduces Appendix B's M₂ = 0.5774 "
                    "and p₂/p₁ = 4.500, and lands the exit on Appendix A's M = 0.40 row."
                ),
            ),
            ValidationCheck(
                name="Shock at exit equals the published normal shock",
                status="PASS",
                detail=(
                    "At the second critical the pre-shock state is the shock-free "
                    "supersonic exit and the jump is normal_shock.solve, to machine "
                    "precision — the same module verified against published Appendix B."
                ),
            ),
            ValidationCheck(
                name="Every relation comes from a verified module",
                status="PASS",
                detail=(
                    "The nozzle restates nothing: area–Mach, the isentropic ratios, the "
                    "normal shock and the mass flow are called, and an audit reads the "
                    "source for the formulas that must not appear in it."
                ),
            ),
            ValidationCheck(
                name="Conservation, at every station and in every regime",
                status="PASS",
                detail=(
                    "ρAV equals the mass flow, T₀ is constant across the shock included, "
                    "and p₀ is constant except for one discrete step at the shock — "
                    "swept over four γ, four area ratios and every regime."
                ),
            ),
            ValidationCheck(
                # NOTE rather than REVIEW: no comparison failed here. The
                # finding is about a worked example in the specification
                # document, and it was corrected before the code was written.
                name="An erratum in the specification, found by this check",
                status="NOTE",
                detail=(
                    "Phase 3 §10.6's worked internal-shock example prints M_e = 0.2358 "
                    "and p_b/p₀ = 0.7584. Those two values lose 38% of the mass flow "
                    "across the exit plane; the section's own pseudocode gives 0.4042 "
                    "and 0.7045, which conserve it exactly. The published example is "
                    "wrong, the implementation follows the pseudocode, and the finding "
                    "is recorded in ERRATUM_PHASE_3_NOZZLE_SHOCK_EXAMPLE.md."
                ),
            ),
        ),
    )
