"""NASA RP-1311 reference cases, as NASA's shipped examples print them.

GENERATED by experiments/solid_propellant_r1/generate_rp1311_reference_cases.py
from ``cea/samples/rp1311/example{5,12,13}.py`` (cea 3.3.4), run
unmodified. Do not edit by hand; re-run the generator.

Each value carries the precision it was printed at, because that is all a
printout can vouch for. The RP-1311 printed tables themselves were not
available offline; the shipped scripts are NASA's executable reproduction of
them, and that is what is cited.
"""

from __future__ import annotations

from .cases import ReferenceCase, ReferenceQuantity, SourceKind

__all__ = [
    "RP1311_EXAMPLE5_PUBLISHED",
    "RP1311_EXAMPLE12_PUBLISHED",
    "RP1311_EXAMPLE13_PUBLISHED",
]


RP1311_EXAMPLE5_PUBLISHED = ReferenceCase(
    case_id="rp1311-example5-published",
    title="NASA RP-1311 Example 5, first pressure column",
    source_kind=SourceKind.NASA_PUBLISHED,
    benchmark_class="A",
    source="NASA RP-1311, Example 5; cea/samples/rp1311/example5.py",
    code="NASA CEA",
    code_version="3.3.4",
    inputs={"example": 5, "column": "first printed column"},
    quantities=(
        ReferenceQuantity("chamber_pressure", 34.023, "atm", decimals=3),
        ReferenceQuantity("chamber_temperature", 2723.021, "K", decimals=3),
        ReferenceQuantity("density", 3.523e-03, "g/cm^3", significant_figures=4),
        ReferenceQuantity("enthalpy", -484.764, "cal/g", decimals=3),
        ReferenceQuantity("entropy", 2.528, "cal/(g*K)", decimals=3),
        ReferenceQuantity("molar_mass", 22.290, "kg/kmol", decimals=3),
        ReferenceQuantity("gamma_s", 1.1928, "1", decimals=4),
        ReferenceQuantity("cp_equilibrium", 0.5781, "cal/(g*K)", decimals=4),
        ReferenceQuantity("cp_frozen", 0.4784, "cal/(g*K)", decimals=4),
        ReferenceQuantity("cv_frozen", 0.3925, "cal/(g*K)", decimals=4),
        ReferenceQuantity("mole_fraction:AL(OH)2", 1.0676e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:AL(OH)2CL", 9.3503e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:AL(OH)3", 3.1749e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALCL", 0.00018397, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALCL2", 2.6227e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALCL3", 5.4338e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALO", 7.2172e-07, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALOCL", 1.3764e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALOH", 0.00015886, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALOHCL", 3.7428e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:ALOHCL2", 0.00028548, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:CL", 0.0016644, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:CO", 0.26455, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:CO2", 0.017784, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:COS", 5.1247e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:H", 0.0058806, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:H2", 0.3215, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:H2O", 0.14651, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:H2S", 0.0013968, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:HCL", 0.13187, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:HCN", 5.8386e-06, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:HCO", 5.8094e-06, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:Mg", 2.8839e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:Mg(OH)2", 1.3237e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:MgCL", 6.4514e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:MgCL2", 0.00099092, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:MgO", 9.3629e-07, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:MgOH", 6.8128e-06, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:N2", 0.068332, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:NH3", 1.4477e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:NO", 2.5828e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:O", 8.1073e-06, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:O2", 1.4888e-06, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:OH", 0.00076625, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:S", 8.5467e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:S2", 2.4708e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:SH", 0.00057907, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:SO", 0.0001519, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:SO2", 5.8746e-05, "1", significant_figures=5),
        ReferenceQuantity("mole_fraction:AL2O3(L)", 0.036724, "1", significant_figures=5),
    ),
    notes=("The one solid-propellant end-to-end benchmark. Not compared, because "
           "RocketForge does not report them: M (1/n), U, G, volume and the "
           "equilibrium Cv. Mole fractions are the species NASA prints (any "
           "column above 5e-6), at %10.5g."),
)


RP1311_EXAMPLE12_PUBLISHED = ReferenceCase(
    case_id="rp1311-example12-published",
    title="NASA RP-1311 Example 12 chamber and c* (not a solid)",
    source_kind=SourceKind.NASA_PUBLISHED,
    benchmark_class="B",
    source="NASA RP-1311, Example 12; cea/samples/rp1311/example12.py",
    code="NASA CEA",
    code_version="3.3.4",
    inputs={"example": 12, "column": "first printed column"},
    quantities=(
        ReferenceQuantity("chamber_pressure", 68.948, "bar", decimals=3),
        ReferenceQuantity("chamber_temperature", 3382.319, "K", decimals=3),
        ReferenceQuantity("characteristic_velocity", 1707.92, "m/s", decimals=2),
    ),
    notes=("A bipropellant rocket problem, used only as a mechanism check on "
           "c* extraction. Its c* is an equilibrium c*: the run freezes from "
           "the throat (n_frz=2, a 1-based station number), after c* is fixed."),
)


RP1311_EXAMPLE13_PUBLISHED = ReferenceCase(
    case_id="rp1311-example13-published",
    title="NASA RP-1311 Example 13 chamber and c* (not a solid)",
    source_kind=SourceKind.NASA_PUBLISHED,
    benchmark_class="B",
    source="NASA RP-1311, Example 13; cea/samples/rp1311/example13.py",
    code="NASA CEA",
    code_version="3.3.4",
    inputs={"example": 13, "column": "first printed column"},
    quantities=(
        ReferenceQuantity("chamber_pressure", 204.138, "atm", decimals=3),
        ReferenceQuantity("chamber_temperature", 3002.540, "K", decimals=3),
        ReferenceQuantity("characteristic_velocity", 6386.75, "ft/s", decimals=2),
    ),
    notes=("A hybrid rocket problem, used only as a mechanism check. NASA's run "
           "passes a BeO(L) insert; its throat sits at BeO's melting point, "
           "2851.000 K, where the answer depends on the starting phase. "
           "RocketForge passes no insert and its c* prints one digit lower "
           "(6386.74 against 6386.75 ft/s): a measured, explained difference, "
           "reported as such rather than tolerated away."),
)
